version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
    labels:
      - dependencies
      - github-actions
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: sbt
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: build
    labels:
      - dependencies
      - sbt
    open-pull-requests-limit: 5
