version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
    labels:
      - dependencies
      - github-actions
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: sbt
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 15
    commit-message:
      prefix: build
    labels:
      - dependencies
      - sbt
    groups:
      apache-beam:
        patterns:
          - "org.apache.beam:*"
      apache-hadoop:
        patterns:
          - "org.apache.hadoop:*"
      apache-log4j:
        patterns:
          - "org.apache.logging.log4j:*"
      netty-four:
        patterns:
          - "io.netty:netty-handler"
          - "io.netty:netty-transport"
      apache-pekko:
        patterns:
          - "org.apache.pekko:*"
      sbt-plugins:
        patterns:
          - "com.eed3si9n:*"
          - "com.github.gseitz:*"
          - "com.github.sbt.junit:sbt-jupiter-interface"
          - "com.jsuereth:*"
          - "org.scalastyle:*"
          - "org.scoverage:*"
          - "org.xerial.sbt:*"
    ignore:
      - dependency-name: "org.scala-sbt:sbt"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "org.webjars:*"
      - dependency-name: "org.webjars.bower:*"
      - dependency-name: "org.webjars.npm:*"
