#!/usr/bin/env bash
##
# Generated by Cloudera Manager and should not be modified directly
##

export GEARPUMP_HOME={{GEARPUMP_HOME}}
export DEFAULT_HADOOP_HOME={{HADOOP_HOME}}

export GEARPUMP_LIBRARY_PATH=${GEARPUMP_HOME}/lib

export HADOOP_HOME=${HADOOP_HOME:-$DEFAULT_HADOOP_HOME}


export HADOOP_CONF_DIR=${HADOOP_CONF_DIR:-/etc/hadoop/conf}


#for f in `ls $GEARPUMP_LIBRARY_PATH`
#do
#   CLASSPATH="$CLASSPATH:$GEARPUMP_LIBRARY_PATH/$f"
#done
#if [ -n "$HADOOP_HOME" ]; then
#  CLASSPATH="$CLASSPATH:${HADOOP_HOME}/lib/native"
#fi
#CLASSPATH="$CLASSPATH:$HADOOP_CONF_DIR"
#export CLASSPATH="/etc/gearpump/conf:$CLASSPATH"
#export PATH=$PATH:$GEARPUMP_HOME/bin
