#!/bin/bash
datetime=$(date "+%Y-%m-%dT%H:%M:%SZ")
for i in $(awk  -F', ' '{printf "{\"id\":\"%s\",\"on\":\"'${datetime}'\",\"body\":\"[%s,%s,%s,%s,%s,%s,%s,%s]\"}\n",$1,$2,$3,$4,$5,$6,$7,$8,$9}' test.csv);do
echo $i | kafka-console-producer --broker-list '10.10.10.46:9092,10.10.10.164:9092,10.10.10.236:9092' --topic $1
done
